Fix a few failures, update tests.

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -18,7 +18,9 @@
 # This file automatically fetches some 'known' files. In case of an api change, the files should
 # be invalid.
 
-source ../src/support
+SAVE=$(pwd)
+
+cd ../src && source support && cd $SAVE
 
 # We override this. We don't want things zipped.
 cbz_make() {
@@ -32,25 +34,27 @@ if [ "$1" = "" ]; then
 	ALL=1
 fi
 
-# Okay as of July 4, 2015
+# Okay as of July 14, 2015
 if [ -f ../src/modules/fakku ]; then
 	if [ ALL = 1 ] || [ "$1" = "fakku" ]; then
 		source ../src/modules/fakku
 		# Nagato Yuki. Non-H.
 		dl_fakku "https://www.fakku.net/doujinshi/if-nagato-yuki-had-disappearances-personality-from-the-start-english"
 		cd "${CHECK_FLDR}"
-		sha512sum -c --quiet "../${CHECK_FLDR}.txt"
-		R=$?
-		if [ $R = 0 ]; then
-			echo "OK!"
-		else
-			echo "Failed."
+		if [ -e "../${CHECK_FLDR}.txt" ]; then
+			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
+			R=$?
+			if [ $R = 0 ]; then
+				echo "OK!"
+			else
+				echo "Failed."
+			fi
 		fi
 		cd ..
 	fi
 fi
 
-# Okay as of July 4, 2015
+# Okay as of July 14, 2015
 if [ -f ../src/modules/eh ]; then
 	if [ ALL = 1 ] || [ "$1" = "eh" ]; then
 		source ../src/modules/eh
@@ -58,65 +62,84 @@ if [ -f ../src/modules/eh ]; then
 		# Updated with a newer version (typo fix, apparently) on July 12, 2015
 		dl_eh "http://g.e-hentai.org/g/824953/944e64d3e5/"
 		cd "${CHECK_FLDR}"
-		sha512sum -c --quiet "../${CHECK_FLDR}.txt"
-		R=$?
-		if [ $R = 0 ]; then
-			echo "OK!"
-		else
-			echo "Failed."
+		if [ -e "../${CHECK_FLDR}.txt" ]; then
+			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
+			R=$?
+			if [ $R = 0 ]; then
+				echo "OK!"
+			else
+				echo "Failed."
+			fi
 		fi
 		cd ..
+
 	fi
 fi
 
 # These we know exist, but still test for existence anyways.
 
-# Okay as of July 4, 2015
+# Okay as of July 14, 2015
 if [ -f ../src/modules/dynsc ]; then
 	if [ ALL = 1 ] || [ "$1" = "dynsc" ]; then
 		source ../src/modules/dynsc
 		# Suika suika. Drunk.
 		dl_dynsc "http://dynasty-scans.com/chapters/suika_suika"
 		cd "${CHECK_FLDR}"
-		sha512sum -c --quiet "../${CHECK_FLDR}.txt"
-		R=$?
-		if [ $R = 0 ]; then
-			echo "OK!"
-		else
-			echo "Failed."
+		if [ -e "../${CHECK_FLDR}.txt" ]; then
+			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
+			R=$?
+			if [ $R = 0 ]; then
+				echo "OK!"
+			else
+				echo "Failed."
+			fi
 		fi
 		cd ..
 	fi
 fi
 
-# Okay as of June 13, 2015
+# Okay as of July 14, 2015
 if [ -f ../src/modules/batoto ]; then
 	if [ ALL = 1 ] || [ "$1" = "batoto" ]; then
 		source ../src/modules/batoto
 		# Medaka Box ch1
 		dl_batoto "http://bato.to/read/_/202832/medaka-box_v1_ch1_by_cxc-scans"
 		cd "${CHECK_FLDR}"
-		sha512sum -c --quiet "../${CHECK_FLDR}.txt"
-		R=$?
-		if [ $R = 0 ]; then
-			echo "OK!"
-		else
-			echo "Failed."
+		if [ -e "../${CHECK_FLDR}.txt" ]; then
+			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
+			R=$?
+			if [ $R = 0 ]; then
+				echo "OK!"
+			else
+				echo "Failed."
+			fi
 		fi
 		cd ..
 	fi
 fi
 
-# Working as of July 4, 2015
+# Working as of July 14, 2015
 if [ -f ../src/modules/mpark ]; then
 	if [ ALL = 1 ] || [ "$1" = "mpark" ]; then
 		source ../src/modules/mpark
 		# New Game. It's new-ish and kinda funny.
 		dl_mpark "http://mangapark.me/manga/new-game-tokunou-shoutarou/s1/v1/c1"
+		cd "${CHECK_FLDR}"
+		if [ -e "../${CHECK_FLDR}.txt" ]; then
+			sha512sum -c --quiet "../${CHECK_FLDR}.txt"
+			R=$?
+			if [ $R = 0 ]; then
+				echo "OK!"
+			else
+				echo "Failed."
+			fi
+		fi
+		cd ..
+
 	fi
 fi
 
-# Okay as of July 4, 2015 (needs a few tweaks tho)
+# Okay as of July 14, 2015 (needs a few tweaks tho)
 if [ -f ../src/modules/foolsl ]; then
 	if [ ALL = 1 ] || [ "$1" = "foolsl" ]; then
 		source ../src/modules/foolsl
@@ -124,15 +147,6 @@ if [ -f ../src/modules/foolsl ]; then
 		dl_foolsl "http://foolrulez.org/slide/reader/read/seitokai_yakuindomo/en/1/1/"
 		# We can't test the 'gimme zip' download...
 		echo "Can't test. This is expected."
-	fi
-fi
-
-# Totally non-functional.
-if [ -f ../src/modules/mread ]; then
-	if [ ALL = 1 ] || [ "$1" = "mread" ]; then
-		source ../src/modules/mread
-		# Ema toyama does some good romcoms.
-		dl_mread "http://www.mangareader.net/440-27882-1/watashi-ni-xx-shinasai/chapter-1.html"
 	fi
 fi
 
