Begin adding scraper functionality (generating chapter batches)

diff --git a/modules/batoto b/modules/batoto
--- a/modules/batoto
+++ b/modules/batoto
@@ -3,8 +3,10 @@
 function auto_batoto() {
 	if [ -n "`echo $1 | grep 'bato.to/' | sed -e 's/^ *//' -e 's/[[:space:]]*$//'`" ]; then
 		# Batoto
-		dl_batoto "$1"
+		return 1
 	fi
+
+	return 0
 }
 
 function dl_batoto() {
@@ -74,4 +76,37 @@ function dl_batoto() {
 	cd ..
 
 	cbz_make $folder
+}
+
+function scrape_batoto() {
+
+	echo -n "[Batoto] Scraping Chapters..."
+
+	wget --user-agent="" --header "Accept-Encoding: identity" --no-cache -nc -t 0 -w 30 "$1" -O scrape.htm > /dev/null 2>&1
+		
+	# Batoto sometimes gives out gunzips. We need to account for that... =_=
+
+	echo `file scrape.htm` | grep 'gzip' - > /dev/null 2>&1
+
+	RET=$?
+
+	# Quirk: GZip. The server ignores our request for non-gz sometimes.
+	if [ $RET == 0 ]; then # Yeah, got a gz.
+		echo -ne "  :/\b\b\b\b"
+
+		mv scrape.htm scrape.htm.gz
+		gunzip scrape.htm.gz
+	fi
+
+	grep '<img src="http://bato.to/book_open.png" style="vertical-align:middle;"' scrape.htm >> batch.txt
+
+	sed -i "s|<a href=\"||g" batch.txt
+	sed -i "s|\"><img src=.*||g" batch.txt
+	sed -ie "s/^[[:space:]]*//" batch.txt
+	sed -ie "s/[[:space:]]*$//" batch.txt
+
+	# We've scraped a batch file from the URL list. Clean up.
+	rm scrape.htm
+
+	echo -e "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b[Batoto] Scraped chapters to batch.txt. You can modify this, or pass it to autobatch."
 }
