Upgrade; more sanity checks.

diff --git a/src/operations/upgrade_self b/src/operations/upgrade_self
--- a/src/operations/upgrade_self
+++ b/src/operations/upgrade_self
@@ -15,8 +15,8 @@ upgrade_self() {
 	fi
 	URL="https://raw.githubusercontent.com/chaoskagami/scangrab/$branch/dist/scangrab.$type"
 	echo "[Upgrade] Checking this scangrab's sha256sum..."
-	this_sha256="$(cat "$0" | sha256sum - | sed "s| .*||g")"
-	gith_sha256="$(fetch "$URL.sha256sum" "-" | sed "s| .*||g")"
+	this_sha256="$(cat "${0}" | sha256sum - | sed "s| .*||g")"
+	gith_sha256="$(fetch "${URL}.sha256sum" "-" | sed "s| .*||g")"
 
 	echo "[Upgrade] Local:  $this_sha256"
 	echo "[Upgrade] Github: $gith_sha256"
@@ -26,18 +26,36 @@ upgrade_self() {
 		exit 0
 	else
 		echo "[Upgrade] Doesn't match upstream. Fetching..."
-		fetch "$URL" "$0"
+		fetch "$URL" "${0}.new"
 		R=$?
 		if [ ! $R = 0 ]; then
 			echo "[Upgrade] Fetch failed. Error code: $R. Do you have write permission?"
 			exit $R
 		fi
-		echo "[Upgrade] We appear to have replaced ourselves. Checking sha256..."
-		this_sha256="$(cat "$0" | sha256sum - | sed "s| .*||g")"
-		if [ "$this_sha256" = "$gith_sha256" ]; then
-			echo "[Upgrade] Succeded."
+		echo "[Upgrade] Downloaded replacement. Checking replacement's sha256sum..."
+		new_sha256="$(cat "${0}.new" | sha256sum - | sed "s| .*||g")"
+		if [ "$new_sha256" = "$gith_sha256" ]; then
+			echo "[Upgrade] Matched. Replacing self..."
+			cp -f "${0}.new" "${0}"
+			R=$?
+			if [ ! $R = 0 ]; then
+				echo "[Upgrade] Couldn't replace. cp error: $R. Abort."
+				rm "${0}.new"
+				exit $R
+			fi
+			echo "[Upgrade] Sync to avoid race conditions..."
+			sync
+			echo "[Upgrade] Checking to make sure it has been replaced..."
+			new_sha256="$(cat "${0}" | sha256sum - | sed "s| .*||g")"
+			if [ ! "$new_sha256" = "$gith_sha256" ]; then
+				echo "[Upgrade] Sanity check failed. This is not normal."
+				exit 1;
+			fi
+			echo "[Upgrade] Succeeded. Exiting."
+			exit 0
 		else
-			echo "[Upgrade] Failed. sha256 does not match github."
+			echo "[Upgrade] Failed. sha256 does not match."
 		fi
 	fi
+	exit 1
 }
