Frontend changes. A lotta them.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -21,53 +21,90 @@ set +H
 
 # Determine operation.
 
-if [ "$1" = "auto" -o "$1" = "a" ]; then
-	# Common operation - Automatic Module Select.
-	shift
-	auto "$@"
-	exit 0
-elif [ "$1" = "batch" -o "$1" = "l" ]; then
-	# Common operation - typed batch.
-	shift
-	batch "$@"
-	exit 0
-elif [ "$1" = "autobatch" -o "$1" = "b" ]; then
-	# Common operation - auto batch.
-	shift
-	autobatch "$@"
-	exit 0
-elif [ "$1" = "scrape" -o "$1" = "s" ]; then
-	# Link scraper.
-	shift
-	scrape "$@"
-	exit 0
-elif [ "$1" = "login" -o "$1" = "u" ]; then
-	# Site login.
-	shift
-	mod_login "$@"
-	exit 0
-elif [ "$1" = "upgrade" ]; then
-	# Upgrade self.
-	upgrade_self
-	exit 0
-else
-	# Not a common operation - either invalid, a module, or a lazy URL.
+# New syntax; default is auto.
+#  -b Batch download
+#  -s Scrape list
+#  -l Login
+#  -U upgrade scangrab
+#  -mModule Use module instead of detection.
 
-	# Detect whether it is a module operation
-	MATCH=""
-	for module in ${MODS[@]}; do
-		if [ "$1" = "$module" ]; then
-			shift
-			dl_${module} "$@"
-			exit 0
-		fi
-	done
-
-	# Try to see if this was a lazy URL as first parameter.
-	auto "$@"
-	R=$?
-	if [ $R = 1 ]; then
-		# All checks failed. Usage~
-		help
+CMD_STR="$1"
+OPERATION=a
+MODULE=a
+TYPE=0
+while [ "${CMD_STR:0:1}" = "-" ]; do
+	if [ ${#CMD_STR} = 2 ]; then
+		case ${CMD_STR:1:1} in
+			b)
+				OPERATION=b ;;
+			s)
+				OPERATION=s ;;
+			l)
+				OPERATION=l ;;
+			U)
+				OPERATION=U ;;
+			u)
+				usage
+				exit 0
+				;;
+			h)
+				help
+				exit 0
+				;;
+			v)
+				VERBOSE=1
+				;;
+			e)
+				# This is used to import functions to a shell.
+				# Not for general use.
+				return 0 # cannot use exit - that would kill the shell
+				;;
+		esac
+	elif [ "${CMD_STR:0:2}" = "-m" ]; then
+		MODULE="${CMD_STR:2}"
+		TYPE=1
 	fi
+	shift
+	CMD_STR="$1"
+done
+
+if [ "$1" = "" ]; then
+	echo "Invalid syntax. See usage (-u) or help (-h) for more info."
+	exit 1
 fi
+
+case $OPERATION in
+	a)
+		if [ $TYPE = 0 ]; then
+			auto "$@"
+		else
+			dl_$MODULE "$@"
+		fi
+		exit 0
+		;;
+	b)
+		batch "$@"
+		exit 0
+		;;
+	s)
+		if [ $TYPE = 0 ]; then
+			scrape "$@"
+		else
+			scrape_$MODULE "$@"
+		fi
+		exit 0
+		;;
+	l)
+		if [ $TYPE = 0 ]; then
+			echo "[scangrab] Please specify a module with the '-m' option."
+			exit 1
+		else
+			mod_login "$MODULE"
+		fi
+		exit 0
+		;;
+	U)
+		upgrade_self
+		exit 0
+		;;
+esac
