Fix some severe mistakes.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -21,25 +21,31 @@ if [ "$1" = "auto" -o "$1" = "a" ]; then
 	# Common operation - Automatic Module Select.
 	shift
 	auto "$@"
+	exit 0
 elif [ "$1" = "batch" -o "$1" = "l" ]; then
 	# Common operation - typed batch.
 	shift
 	batch "$@"
+	exit 0
 elif [ "$1" = "autobatch" -o "$1" = "b" ]; then
 	# Common operation - auto batch.
 	shift
 	autobatch "$@"
+	exit 0
 elif [ "$1" = "scrape" -o "$1" = "s" ]; then
 	# Link scraper.
 	shift
 	scrape "$@"
+	exit 0
 elif [ "$1" = "login" -o "$1" = "u" ]; then
 	# Site login.
 	shift
 	mod_login "$@"
+	exit 0
 elif [ "$1" = "upgrade" ]; then
 	# Upgrade self.
 	upgrade_self
+	exit 0
 else
 	# Not a common operation - either invalid, a module, or a lazy URL.
 
@@ -49,12 +55,15 @@ else
 		if [ "$1" = "$module" ]; then
 			shift
 			dl_${module} "$@"
+			exit 0
 		fi
 	done
 
 	# Try to see if this was a lazy URL as first parameter.
 	auto "$@"
-
-	# All checks failed. Usage~
-	help
+	R=$?
+	if [ $R = 1 ]; then
+		# All checks failed. Usage~
+		help
+	fi
 fi
